#!/bin/csh

pdflatex liamthesis.tex
cat thesisNotes.bib | grep -v REVTEX > thesisNotes.bib
#bibtex thesis; pdflatex thesis; pdflatex thesis
rm *.aux *.dvi *.log *.blg *.out
rm sections/*.aux
open liamthesis.pdf

